[package]
name = "frappe-tea"
version = "0.0.0"
edition = "2021"
description = "Framework founded upon Functional Reactivity with the Elm Architecture, VDOM-less, providing unseen performance, reliability, and testability."
repository = "https://github.com/jquesada2016/frappe-tea"
authors = ["Jose Quesada <jquesada2016@fau.edu>"]
keywords = ["frp", "elm", "frontend", "framework", "ssr"]
license = "MIT"
categories = ["gui", "no-std", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aquamarine = "0.1"
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = []